### PR TITLE
Update resources.html

### PR DESCRIPTION
**Pull request by 2hot2exist**
Hardware 2FA section updated.

### CODE REVIEW

**Comment by 2hot2exist** [comment]
I have added the social platforms section.

**Comment by 2hot2exist** [comment]
Place to view the changes: https://2hot2exist.github.io/website/resources

**Comment by henryistaken** [comment]
First, thanks for the patience as I get caught up here on GH. It's been far too long!

1. Love the notes you added to the U2F section
2. I also love the addition of the social platforms section. However, there's a fine line for our resources page between us suggesting privacy/security tools, and us suggesting alternatives to all software/services. This one for me lands in the latter. I'm not trying to have our resources be a service like alternativeto.net, because it's already such a great website that we could never compete with. So we'd rather recommended people to alternativeto.net (which is in our resources) for things like this. It's the same reason we don't put "productivity services" or "note taking software" or "video platforms" or "production software" on our website - they are not strictly privacy/security tools - but rather just more privacy/security-friendly versions of software people are using.

I know it took you some time to put that section together, but if you wanted to exclude the social networks, I can go ahead and approve this PR w/ just the U2F notes!

**Review by henryistaken — APPROVED** [review]

**Comment by henryistaken** [comment]
https://github.com/techlore/website/commit/0683c5e0093fdf97c9fbc580c5b99b3d31f1534b
Went ahead and pushed this in its own PR to be a bit cleaner

**Pull request closed without merging**
