### PR TITLE
Just updated 2023 to 2024

### PR DESCRIPTION
**Pull request by agrofx1**

### CODE REVIEW

**Review by jordan-warne — COMMENTED** [review]
A way to improve this so that we don't need to do a pull request every year is that you can use JavaScript to automatically get the current year.

`<script>document.write(new Date().getFullYear())</script>`

**Comment by agrofx1** [comment]
Good solution!

**Comment by henry-fisher** [comment]
Thanks you two!

**Comment by agrofx1** [comment]
I've just changed(
`$('#year').html(new Date().getFullYear());`

**Pull request merged**
