### PR TITLE
Hide.me updates

### PR DESCRIPTION
**Pull request by 8pen-s8urce**
**Warrant canary**: Doesn't seem to exist. One post published by Hide.me in its official community forum in 2015, the company didn't seem to consider a warrant canary useful to them due to being based in Malaysia, instead of being based in the USA.

Relevant question from the referenced post:
"7. Does your company have a warrant canary or a similar solution to alert customers to gag orders?"

Hide.me answer:
"7. Since we are not operating under US law, in Malaysia there is no such thing as the Patriot Act. So far we haven’t been served with a court order or any governmental request and if it was the case we would be transparent with our customers that might have been affected by such court order."

Source:
https://community.hide.me/threads/torrentfreak-questionnaire-about-different-vpn-services-and-anonymity.2040/

Also, an article published by TorrentFreak in July 2023 lists some questions asked in 2023 to different VPN companies, including Hide.me, and their answers.
Hide.me answered the sixth question without mentioning a Warrant Canary, which makes me assume that Hide.me doesn't have a warrant canary.

The question:
"6. What steps would be taken in the event a court orders your company to identify an active or former user of your service? How would your company respond to a court order that requires you to log activity for a user going forward? Have these scenarios ever played out in the past?"

Hide.me answer:
"6. Although it has never happened in such a scenario, we won’t be able to entertain the court orders because our infrastructure is built in a way that it does not store any logs, and there is no way we could link any particular cyber activity to any particular user. In case, we are forced to store user logs, we would prefer to close down rather than putting our users at stake who have put their trust in us."

Source: https://torrentfreak.com/best-vpn-anonymous-no-logging/#hideme

The official hide.me website doesn't have any information about Warrant Canaries and I couldn't find anything when searching about hide.me and warrant canaries, so I assume that hide.me doesn't have a warrant canary.

**Max Data Encryption**: AES 256
Source: https://hide.me/en/features/wifi-security 

**Max Handshake Encryption**: RSA 8192 bit, including by default, at least with Open VPN.
Sources:
https://community.hide.me/threads/rsa-handshake.2769/ (2016 hide.me official thread in hide.me's official community forum)
https://torrentfreak.com/best-vpn-anonymous-no-logging/#hideme (2023 TorrentFreak article, official answer given by Hide.me to the ninth question)
https://github.com/eventure/hide.client.routers?tab=readme-ov-file#known-issues (mentions the RSA 8192 bit keys used by Hide.me VPN servers)

I don't know what applies to the other VPN protocols offered by Hide.me VPN: Wireguard, SoftEther, IKEv2 and SSTP.
More information about the protocols and their characteristics, including platform availability:
https://hide.me/en/features/vpn-protocols

**Anon Payments**: XMR (Monero) and other cryptocurrencies are accepted for payments.
Source: https://hide.me/en/knowledgebase/which-payment-methods-do-you-support/

**1st-Party Servers**: Hide.me doesn't own any server of its VPN or DNS infrastructure, all Hide.me VPN and DNS servers are rented.
Source: https://torrentfreak.com/best-vpn-anonymous-no-logging/#hideme (the eleventh answer by Hide.me)

**Server count**: 2600. 
Source: https://hide.me/en/press

The following source mentions "+2600 servers", but I think that is simply misleading marketing, otherwise my previous source is outdated/too simplified.
Source: https://hide.me/en/why-hideme

**Total countries**: 56.
Source: https://hide.me/en/press

Edit.:
**Connect on boot**: Available in all major platforms.
Sources:

Android: https://hide.me/en/knowledgebase/how-to-configure-auto-connect-on-android/

iOS (at the time of writing this, the fifth screenshot shows that the auto connect feature is available in iOS): https://apps.apple.com/us/app/hide-me-vpn/id953040671?platform=iphone

Windows: https://hide.me/en/knowledgebase/how-to-configure-auto-connect-on-windows/

MacOS (this is the only source I could find that specifies auto connect support for MacOS): https://community.hide.me/threads/automatically-connect-to-vpn-on-startup.30/

Linux: https://hide.me/en/software/linux

### CODE REVIEW

**Comment by jordan-warne** [comment]
> A good idea would be to ask customer support about this, but I am unsure if I will do it myself. As such, for now, I think it's better to keep the question mark as it is.

I sent a support ticket and asked them about this, will update once I get a response.

> I added a commit to change the Hide.me audit section of the techlore VPN chart from "Yes" to "Android only" due to reasons stated in previous comments of this conversation, with the main point being that this seems a more accurate description of the audit that the Hide.me VPN Android app went through.

I agree this is the correct way to do this, once their other clients & server backend have been audited then we can update it to "Yes".

**Review by jordan-warne — CHANGES_REQUESTED** [review]
Everything looks good here, great work and thanks for the updates 😃 once we have an update on their diskless servers we can merge this.

**Comment by jordan-warne** [comment]
Okay heard back from hide.me

Their support told me that they exclusively use RAM based servers.
Screenshot 2024-06-16 at 8 29 41 AM

**Review by jordan-warne — APPROVED** [review]

**Comment by henry-fisher** [comment]
Thank you everyone for digging into this. I know how annoying it can be to try and consolidate all the data from each provider.

**Pull request merged**
